name: Test actions
on:
  push:
    paths:
      - .github/actions/**
      - .github/workflows/test-actions.yml
  pull_request:
    paths:
      - .github/actions/**
      - .github/workflows/test-actions.yml
jobs:
  test-clean-runner:
    name: Test clean-runner action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test clean-runner
        uses: ./.github/actions/clean-runner

  test-download-aur-pkgbase:
    name: Test download-aur-pkgbase action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test download-aur-pkgbase
        uses: ./.github/actions/download-aur-pkgbase
        with:
          pkgbase: yay
          dest: startdir

      - name: Check result
        run: test -f startdir/PKGBUILD

  test-fetch-gpg-fingerprints:
    name: Test fetch-gpg-fingerprints action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test fetch-gpg-fingerprints
        uses: ./.github/actions/fetch-gpg-fingerprints
        with:
          fingerprints: |
            3F59043BE267E1B1177688AC8F6DE3D614FCFD7A
            E1096BCBFF6D418796DE78515384CE82BA52C83A

      - name: Check result
        run: |
          test -f keys/pgp/E1096BCBFF6D418796DE78515384CE82BA52C83A.asc
          test -f keys/pgp/3F59043BE267E1B1177688AC8F6DE3D614FCFD7A.asc

  test-upload-artifacts:
    name: Test upload-artifacts action when changed
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate data to upload
        run: touch temp:invalid.txt

      - name: Test upload-artifacts
        uses: ./.github/actions/upload-artifacts
        id: upload
        with:
          name: temp-upload
          path: temp:invalid.txt

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: temp-upload

      - name: Check result
        run: test -f temp-upload.tar

      # https://github.com/actions/upload-artifact/issues/290#issuecomment-1374207010
      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE -H 'Accept: application/vnd.github+json' \
            '/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload.outputs.artifact-id }}'

  test-download-artifacts:
    name: Test download-artifacts action when changed
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate data to upload
        run: |
          touch temp:invalid.txt
          tar -cvpf temp.tar temp:invalid.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: temp-download
          path: temp.tar

      - name: Test download-artifacts(by name)
        uses: ./.github/actions/download-artifacts
        with:
          names: temp-download
          path: by-name

      - name: Test download-artifacts(by id)
        uses: ./.github/actions/download-artifacts
        with:
          artifact-ids: ${{ steps.upload.outputs.artifact-id }}
          path: by-id

      - name: Check result
        run: |
          test -f by-name/temp:invalid.txt
          test -f by-id/temp:invalid.txt

      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE -H 'Accept: application/vnd.github+json' \
            '/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload.outputs.artifact-id }}'

  test-build-package:
    name: Test build-package action when changed.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/makepkg:${{ github.sha }}

      - name: Test build-package
        uses: ./.github/actions/build-package
        with:
          where: packages/flatpak-builder-tools-git

      - name: Check result
        run: |
          test -d pkgdest
          test "$(ls pkgdest/*.pkg.tar.* | wc -l)" -gt 0
          test -d logdest
          test "$(ls logdest/*.log | wc -l)" -gt 0
          test -d srcdest
          test "$(ls srcdest/* | wc -l)" -gt 0
