name: Test actions
on:
  push:
    paths:
      - .github/actions/**
      - .github/workflows/test-actions.yml
  pull_request:
    paths:
      - .github/actions/**
      - .github/workflows/test-actions.yml
  workflow_dispatch:
jobs:
  test-clean-runner:
    name: Test clean-runner action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test clean-runner
        uses: ./.github/actions/clean-runner

  test-download-aur-pkgbase:
    name: Test download-aur-pkgbase action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test download-aur-pkgbase
        uses: ./.github/actions/download-aur-pkgbase
        with:
          pkgbase: yay
          dest: startdir

      - name: Check result
        run: test -f startdir/PKGBUILD

  test-fetch-gpg-fingerprints:
    name: Test fetch-gpg-fingerprints action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test fetch-gpg-fingerprints
        uses: ./.github/actions/fetch-gpg-fingerprints
        with:
          fingerprints: |
            3F59043BE267E1B1177688AC8F6DE3D614FCFD7A
            E1096BCBFF6D418796DE78515384CE82BA52C83A

      - name: Check result
        run: |
          test -f keys/pgp/E1096BCBFF6D418796DE78515384CE82BA52C83A.asc
          test -f keys/pgp/3F59043BE267E1B1177688AC8F6DE3D614FCFD7A.asc

  test-upload-artifacts:
    name: Test upload-artifacts action when changed
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate data to upload
        run: touch temp:invalid.txt

      - name: Test upload-artifacts
        uses: ./.github/actions/upload-artifacts
        id: upload
        with:
          name: temp-upload
          path: temp:invalid.txt

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: temp-upload

      - name: Check result
        run: test -f temp-upload.tar

      # https://github.com/actions/upload-artifact/issues/290#issuecomment-1374207010
      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE -H 'Accept: application/vnd.github+json' \
            '/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload.outputs.artifact-id }}'

  test-download-artifacts:
    name: Test download-artifacts action when changed
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate data to upload
        run: |
          touch temp:invalid.txt
          tar -cvpf temp.tar temp:invalid.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: temp-download
          path: temp.tar

      - name: Test download-artifacts(by name)
        uses: ./.github/actions/download-artifacts
        with:
          names: temp-download
          path: by-name

      - name: Test download-artifacts(by id)
        uses: ./.github/actions/download-artifacts
        with:
          artifact-ids: ${{ steps.upload.outputs.artifact-id }}
          path: by-id

      - name: Check result
        run: |
          test -f by-name/temp:invalid.txt
          test -f by-id/temp:invalid.txt

      - name: Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE -H 'Accept: application/vnd.github+json' \
            '/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload.outputs.artifact-id }}'

  test-apply-patches:
    name: Test apply-patches action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get PKGBUILD
        uses: ./.github/actions/download-aur-pkgbase
        with:
          pkgbase: ruffle-nightly
          dest: ruffle-nightly

      - name: Test apply-patches
        uses: ./.github/actions/apply-patches
        with:
          where: ruffle-nightly
          pkgbase: ruffle-nightly

      - name: Check result
        working-directory: ruffle-nightly
        run: '! git --no-pager diff --exit-code'

  test-build-makepkg:
    name: Test build-makepkg action when changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test build-makepkg
        id: build
        uses: ./.github/actions/build-makepkg

      - name: Check result
        run: test -f '${{ steps.build.outputs.image-path }}'

  test-execute-makepkg:
    name: Test execute-makepkg action when changed
    runs-on: ubuntu-latest
    needs: test-download-aur-pkgbase
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build makepkg
        uses: docker/build-push-action@v6
        with:
          context: ./.github/actions/build-makepkg
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/makepkg:${{ github.sha }}

      - name: Get PKGBUILD
        uses: ./.github/actions/download-aur-pkgbase
        with:
          pkgbase: aria2cd
          dest: ${{ github.workspace }}/aria2cd

      - name: Test execute-makepkg
        id: makepkg
        uses: ./.github/actions/execute-makepkg
        with:
          where: ${{ github.workspace }}/aria2cd
          args: --printsrcinfo

      - name: Check result
        run: diff -u '${{ github.workspace }}/aria2cd/.SRCINFO' '${{ steps.makepkg.outputs.stdout-path }}'

  test-get-package-status:
    name: Test get-package-status action when changed
    needs: test-download-aur-pkgbase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get PKGBUILD
        uses: ./.github/actions/download-aur-pkgbase
        with:
          pkgbase: aria2cd
          dest: ${{ github.workspace }}/aria2cd

      - name: Get srcinfo
        id: srcinfo
        run: |
          {
            EOF="$(dd if=/dev/urandom bs=15 count=1 status=none | base64)"
            echo "srcinfo<<$EOF"
            cat '${{ github.workspace }}/aria2cd/.SRCINFO'
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Get package status
        id: status
        uses: ./.github/actions/get-package-status
        with:
          srcinfo: ${{ steps.srcinfo.outputs.srcinfo }}

      - name: Check result
        if: steps.status.outputs.built == 'true'
        run: ls -l pkgdest/*.pkg.tar.*

  test-setup-makepkg:
    name: Test setup-makepkg action when changed
    needs: test-build-makepkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build makepkg
        id: build
        uses: ./.github/actions/build-makepkg

      - name: Test setup-makepkg
        uses: ./.github/actions/setup-makepkg
        with:
          image-path: ${{ steps.build.outputs.image-path }}

      - name: Check result
        run: test ! -f '${{ steps.build.outputs.image-path }}'
